[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/api/*"
  to     = "https://insure-claim-vision.onrender.com/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/static/*"
  to     = "https://insure-claim-vision.onrender.com/static/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
